<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-12-21 15:37

$extensionPath = t3lib_extMgm::extPath('abz_developer');
return array(
	'tx_abzdeveloper' => $extensionPath . 'class.tx_abzdeveloper.php',
	'tx_abzdeveloper_cache' => $extensionPath . 'hooks/index_ts.php',
	'tx_abzdeveloper_report_cachestatus' => $extensionPath . 'report/class.tx_abzdeveloper_report_cachestatus.php',
);
?>